name: ics
version: 0.1.0
description: >-
  Serializes and Deserializes ICalendar text. Offers 99+% coverage of the ICalendar RFC.
homepage: https://github.com/RoadTripMoustache/i_calendar
repository: https://github.com/RoadTripMoustache/i_calendar
issue_tracker: https://github.com/RoadTripMoustache/i_calendar/issues
environment:
  sdk: '>=3.0.5 <4.0.0'
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

index_generator:
  default_file_name: i_calendar
  libraries:
    - directory_path: lib
      include:
        - "src/**"

dependencies:
  email_validator: ^3.0.0
  equatable: ^2.0.8
  intl: ^0.20.2
  nanoid: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  index_generator: ^4.1.2
  test: ^1.30.0
